name: Reusable workflow

on:
  workflow_call:
    inputs: 
      who-to-greet:
      description: 'the person to be greeted'
      type: string
      required: true
      default: World
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    echo "
