name: Reusable workflow

on:
  workflow_call:
    inputs: 
      who-to-greet:
      description: 'the person to be greeted'
      type: string
      required: true
      default: World
  outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hello $${inputs.who-to-greet}}" 
     - name: Set Time
       id: timeID
       run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.timeID.outputs.time }}
     

